version: '2.3'

services:
  node:
    build: .
    container_name: breedog
    restart: always
    ports:
      - 3000:3000
      - 80:8080
    volumes:
      - ./:/var/breedog 
      - /var/api/node_modules
      - /var/frontend/node_modules